name: Publish Chrome Extension

on:
  push:
    branches:
      - production  # Trigger only on the 'production' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Specify the Node.js version


    - name: Zip the chrome_extension folder
      run: |
        zip -r extension.zip chrome_extension/*  # Zip all files in the chrome_extension folder

    - name: Install chrome-webstore-upload
      run: npm install chrome-webstore-upload

    - name: Upload to Chrome Web Store
      env:
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        APP_ID: ${{ secrets.CHROME_APP_ID }}
      run: |
        npx chrome-webstore-upload upload --source ./extension.zip \
          --app-id $APP_ID \
          --client-id $CLIENT_ID \
          --client-secret $CLIENT_SECRET \
          --refresh-token $REFRESH_TOKEN

    - name: Publish Extension
      env:
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        APP_ID: ${{ secrets.CHROME_APP_ID }}
      run: |
        npx chrome-webstore-upload publish \
          --app-id $APP_ID \
          --client-id $CLIENT_ID \
          --client-secret $CLIENT_SECRET \
          --refresh-token $REFRESH_TOKEN
