name: Publish Chrome Extension

on:
  push:
    branches:
      - production  # Trigger only on the 'production' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install zip tool
      run: sudo apt-get install -y zip

    - name: Zip the chrome_extension folder
      run: |
        cd chrome_extension  # Navigate to the chrome_extension folder
        zip -r ../extension.zip *  # Zip all files and subfolders inside

    - name: Install chrome-webstore-upload
      run: npm install -g chrome-webstore-upload

    - name: Upload to Chrome Web Store
      env:
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        APP_ID: ${{ secrets.CHROME_APP_ID }}
      run: |
        chrome-webstore-upload upload --source ./extension.zip \
          --app-id $APP_ID \
          --client-id $CLIENT_ID \
          --client-secret $CLIENT_SECRET \
          --refresh-token $REFRESH_TOKEN

    - name: Publish Extension
      env:
        CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        APP_ID: ${{ secrets.CHROME_APP_ID }}
      run: |
        chrome-webstore-upload publish \
          --app-id $APP_ID \
          --client-id $CLIENT_ID \
          --client-secret $CLIENT_SECRET \
          --refresh-token $REFRESH_TOKEN
